In [1]:
import pandas as pd
matches = pd.read_csv("matches.csv", index_col=0)
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,Match Report,NaN,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,Match Report,NaN,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,Match Report,NaN,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal

In [2]:
matches.shape

(4198, 27)

In [3]:
# 2 seasons * 20 squads * 38 matches

2 * 20 * 38

1520

In [4]:
# Matches played
matches["team"].value_counts()

Tottenham Hotspur           211
Chelsea                     210
Southampton                 210
West Ham United             210
Manchester City             210
Leicester City              210
Crystal Palace              210
Everton                     210
Manchester United           210
Newcastle United            210
Liverpool                   209
Brighton and Hove Albion    209
Arsenal                     209
Burnley                     190
Wolverhampton Wanderers     172
Watford                     152
Aston Villa                 134
Bournemouth                 134
Fulham                       97
Leeds United                 95
Norwich City                 76
West Bromwich Albion         76
Sheffield United             76
Huddersfield Town            76
Brentford                    58
Cardiff City                 38
Swansea City                 38
Stoke City                   38
Nottingham Forest            20
Name: team, dtype: int64

In [5]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2017-08-12,12:30,Premier League,Matchweek 1,Sat,Away,D,3.0,3.0,Watford,...,Match Report,NaN,13.0,4.0,13.9,0.0,1.0,1.0,2018,Liverpool
2,2017-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,23.0,13.0,18.6,2.0,0.0,0.0,2018,Liverpool
4,2017-08-27,16:00,Premier League,Matchweek 3,Sun,Home,W,4.0,0.0,Arsenal,...,Match Report,NaN,18.0,10.0,15.9,0.0,0.0,0.0,2018,Liverpool
5,2017-09-09,12:30,Premier League,Matchweek 4,Sat,Away,L,0.0,5.0,Manchester City,...,Match Report,NaN,7.0,3.0,20.5,2.0,0.0,0.0,2018,Liverpool
7,2017-09-16,15:00,Premier League,Matchweek 5,Sat,Home,D,1.0,1.0,Burnley,...,Match Report,NaN,35.0,9.0,20.6,0.0,0.0,0.0,2018,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23,2022-12-26,17:30,Premier League,Matchweek 17,Mon,Away,W,3.0,1.0,Aston Villa,...,Match Report,NaN,16.0,9.0,17.0,0.0,0.0,0.0,2023,Liverpool
24,2022-12-30,20:00,Premier League,Matchweek 18,Fri,Home,W,2.0,1.0,Leicester City,...,Match Report,NaN,21.0,5.0,18.4,1.0,0.0,0.0,2023,Liverpool
25,2023-01-02,17:30,Premier League,Matchweek 19,Mon,Away,L,1.0,3.0,Brentford,...,Match Report,NaN,16.0,5.0,15.3,0.0,0.0,0.0,2023,Liverpool
27,2023-01-14,15:00,Premier League,Matchweek 20,Sat,Away,L,0.0,3.0,Brighton,...,Match Report,NaN,6.0,2.0,12.8,0.0,0.0,0.0,2023,Liverpool
29,2023-01-21,12:30,Premier League,Matchweek 21,Sat,Home,D,0.0,0.0,Chelsea,...,Match Report,NaN,15.0,3.0,15.5,0.0,0.0,0.0,2023,Liverpool

In [6]:
matches["round"].value_counts()

Matchweek 1     120
Matchweek 14    120
Matchweek 21    120
Matchweek 20    120
Matchweek 19    120
Matchweek 18    120
Matchweek 17    120
Matchweek 16    120
Matchweek 15    120
Matchweek 13    120
Matchweek 11    120
Matchweek 10    120
Matchweek 9     120
Matchweek 6     120
Matchweek 5     120
Matchweek 4     120
Matchweek 3     120
Matchweek 2     120
Matchweek 12    118
Matchweek 8     114
Matchweek 7     106
Matchweek 22    100
Matchweek 32    100
Matchweek 37    100
Matchweek 33    100
Matchweek 36    100
Matchweek 35    100
Matchweek 34    100
Matchweek 30    100
Matchweek 31    100
Matchweek 23    100
Matchweek 29    100
Matchweek 28    100
Matchweek 27    100
Matchweek 26    100
Matchweek 25    100
Matchweek 24    100
Matchweek 38    100
Name: round, dtype: int64

In [7]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [8]:
#del matches["comp"]
#del matches["notes"]
matches["date"] = pd.to_datetime(matches["date"])
matches["target"] = (matches["result"] == "W").astype("int")
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,target
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,NaN,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal,1
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,NaN,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal,1
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,NaN,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal,1
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,NaN,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal,1
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,NaN,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2018-04-15,16:00,Premier League,Matchweek 34,Sun,Away,W,1.0,0.0,Manchester Utd,...,NaN,10.0,4.0,18.1,0.0,0.0,0.0,2018,West Bromwich Albion,1
39,2018-04-21,12:30,Premier League,Matchweek 35,Sat,Home,D,2.0,2.0,Liverpool,...,NaN,13.0,6.0,17.7,0.0,0.0,0.0,2018,West Bromwich Albion,0
40,2018-04-28,15:00,Premier League,Matchweek 36,Sat,Away,W,1.0,0.0,Newcastle Utd,...,NaN,9.0,2.0,20.1,0.0,0.0,0.0,2018,West Bromwich Albion,1
41,2018-05-05,15:00,Premier League,Matchweek 37,Sat,Home,W,1.0,0.0,Tottenham,...,NaN,9.0,1.0,10.2,0.0,0.0,0.0,2018,West Bromwich Albion,1
42,2018-05-13,15:00,Premier League,Matchweek 38,Sun,Away,L,0.0,2.0,Crystal Palace,...,NaN,7.0,1.0,24.8,1.0,0.0,0.0,2018,West Bromwich Albion,0

In [9]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")
matches["day_code"] = matches["date"].dt.dayofweek
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,1.0,0.0,0.0,2023,Arsenal,1,0,8,20,4
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,0.0,0.0,0.0,2023,Arsenal,1,1,13,15,5
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,0.0,0.0,0.0,2023,Arsenal,1,0,2,17,5
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,1.0,0.0,0.0,2023,Arsenal,1,1,10,17,5
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,1.0,0.0,0.0,2023,Arsenal,1,1,1,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2018-04-15,16:00,Premier League,Matchweek 34,Sun,Away,W,1.0,0.0,Manchester Utd,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,0,16,16,6
39,2018-04-21,12:30,Premier League,Matchweek 35,Sat,Home,D,2.0,2.0,Liverpool,...,0.0,0.0,0.0,2018,West Bromwich Albion,0,1,14,12,5
40,2018-04-28,15:00,Premier League,Matchweek 36,Sat,Away,W,1.0,0.0,Newcastle Utd,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,0,17,15,5
41,2018-05-05,15:00,Premier League,Matchweek 37,Sat,Home,W,1.0,0.0,Tottenham,...,0.0,0.0,0.0,2018,West Bromwich Albion,1,1,24,15,5
42,2018-05-13,15:00,Premier League,Matchweek 38,Sun,Away,L,0.0,2.0,Crystal Palace,...,1.0,0.0,0.0,2018,West Bromwich Albion,0,0,8,15,6

In [10]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)
train = matches[matches["date"] < '2022-01-01']
test = matches[matches["date"] > '2022-01-01']
predictors = ["venue_code", "opp_code", "hour", "day_code"]
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [11]:
preds = rf.predict(test[predictors])
from sklearn.metrics import accuracy_score
error = accuracy_score(test["target"], preds)
error

0.6106870229007634

In [12]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          370  109
1          197  110

In [13]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.502283105022831

In [14]:
grouped_matches = matches.groupby("team")
group = grouped_matches.get_group("Manchester City").sort_values("date")
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]


grouped_matches = matches.groupby("team")


rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2017-09-09,12:30,Premier League,Matchweek 4,Sat,Home,W,5.0,0.0,Liverpool,...,12,5,1.666667,0.666667,17.333333,6.000000,18.566667,1.333333,0.000000,0.000000
5,2017-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,6.0,0.0,Watford,...,15,5,2.666667,0.666667,17.000000,8.000000,16.733333,0.666667,0.000000,0.000000
7,2017-09-23,15:00,Premier League,Matchweek 6,Sat,Home,W,5.0,0.0,Crystal Palace,...,15,5,4.333333,0.333333,19.666667,9.000000,15.800000,0.333333,0.333333,0.333333
9,2017-09-30,17:30,Premier League,Matchweek 7,Sat,Away,W,1.0,0.0,Chelsea,...,17,5,5.333333,0.000000,21.666667,9.333333,14.900000,0.000000,0.333333,0.333333
10,2017-10-14,15:00,Premier League,Matchweek 8,Sat,Home,W,7.0,2.0,Stoke City,...,15,5,4.000000,0.000000,23.000000,7.666667,16.233333,0.333333,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,2022-12-31,15:00,Premier League,Matchweek 18,Sat,Home,D,1.0,1.0,Everton,...,15,5,2.000000,1.333333,23.333333,6.333333,18.333333,0.333333,0.333333,0.333333
25,2023-01-05,20:00,Premier League,Matchweek 19,Thu,Away,W,1.0,0.0,Chelsea,...,20,3,1.666667,1.333333,23.666667,6.000000,17.433333,0.000000,0.000000,0.000000
28,2023-01-14,12:30,Premier League,Matchweek 20,Sat,Away,L,1.0,2.0,Manchester Utd,...,12,5,1.666667,0.666667,18.000000,5.000000,15.800000,0.000000,0.000000,0.000000
29,2023-01-19,20:00,Premier League,Matchweek 7,Thu,Home,W,4.0,2.0,Tottenham,...,20,3,1.000000,1.000000,11.000000,2.333333,16.866667,0.000000,0.000000,0.000000
30,2023-01-22,14:00,Premier League,Matchweek 21,Sun,Home,W,3.0,0.0,Wolves,...,14,6,2.000000,1.333333,11.000000,3.333333,17.166667,0.333333,0.000000,0.000000

In [15]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2017-09-09  15:00  Premier League   Matchweek 4
                        6  2017-09-17  13:30  Premier League   Matchweek 5
                        8  2017-09-25  20:00  Premier League   Matchweek 6
                        10 2017-10-01  12:00  Premier League   Matchweek 7
                        11 2017-10-14  17:30  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 18 2022-12-26  15:00  Premier League  Matchweek 17
                        19 2022-12-31  12:30  Premier League  Matchweek 18
                        20 2023-01-04  20:00  Premier League  Matchweek 19
                        23 2023-01-14  15:00  Premier League  Matchweek 20
                        25 2023-01-22  14:00  Premier League  Matchweek 21

                            day venue result   gf   ga         opponent  ...  \
team                                                                     ...
Arsenal                 4   Sat  Home      W  3.0  0.0      Bournemouth  ...
                        6   Sun  Away      D  0.0  0.0          Chelsea  ...
                        8   Mon  Home      W  2.0  0.0        West Brom  ...
                        10  Sun  Home      W  2.0  0.0         Brighton  ...
                        11  Sat  Away      L  1.0  2.0          Watford  ...
...                         ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 18  Mon  Away      W  2.0  1.0          Everton  ...
                        19  Sat  Home      L  0.0  1.0   Manchester Utd  ...
                        20  Wed  Away      D  1.0  1.0      Aston Villa  ...
                        23  Sat  Home      W  1.0  0.0         West Ham  ...
                        25  Sun  Away      L  0.0  3.0  Manchester City  ...

                            hour  day_code  gf_rolling  ga_rolling sh_rolling  \
team
Arsenal                 4     15         5    1.333333    2.666667  17.666667
                        6     13         6    1.000000    1.666667  14.333333
                        8     20         0    1.000000    1.333333  12.000000
                        10    12         6    1.666667    0.000000  14.333333
                        11    17         5    1.333333    0.000000  17.000000
...                          ...       ...         ...         ...        ...
Wolverhampton Wanderers 18    15         0    1.000000    2.000000  10.333333
                        19    12         5    1.333333    2.000000   8.333333
                        20    20         2    0.666667    1.333333   9.333333
                        23    15         5    1.000000    1.000000   9.000000
                        25    14         6    0.666667    0.666667  12.333333

                           sot_rolling dist_rolling fk_rolling  pk_rolling  \
team
Arsenal                 4     5.333333    18.133333   0.000000    0.000000
                        6     5.000000    16.766667   0.333333    0.000000
                        8     3.666667    16.566667   0.333333    0.000000
                        10    5.333333    17.400000   1.333333    0.333333
                        11    5.000000    18.333333   1.666667    0.333333
...                                ...          ...        ...         ...
Wolverhampton Wanderers 18    3.333333    19.566667   0.333333    0.333333
                        19    3.333333    18.966667   0.333333    0.333333
                        20    3.000000    18.633333   1.000000    0.000000
                        23    3.333333    16.700000   0.666667    0.000000
                        25    3.333333    17.166667   0.666667    0.000000

                            pkatt_rolling
team
Arsenal                 4        0.000000
                        6        0.000000
                        8        0.000000
                        10       0.333333
                        11       0.333333
...                                   ...
Wolverhampton Wanderers 18       0.333333
                        19       0.333333
                        20       0.000000
                        23       0.000000
                        25       0.000000

[4102 rows x 40 columns]

In [16]:
matches_rolling = matches_rolling.droplevel('team')
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2017-09-09,15:00,Premier League,Matchweek 4,Sat,Home,W,3.0,0.0,Bournemouth,...,15,5,1.333333,2.666667,17.666667,5.333333,18.133333,0.000000,0.000000,0.000000
6,2017-09-17,13:30,Premier League,Matchweek 5,Sun,Away,D,0.0,0.0,Chelsea,...,13,6,1.000000,1.666667,14.333333,5.000000,16.766667,0.333333,0.000000,0.000000
8,2017-09-25,20:00,Premier League,Matchweek 6,Mon,Home,W,2.0,0.0,West Brom,...,20,0,1.000000,1.333333,12.000000,3.666667,16.566667,0.333333,0.000000,0.000000
10,2017-10-01,12:00,Premier League,Matchweek 7,Sun,Home,W,2.0,0.0,Brighton,...,12,6,1.666667,0.000000,14.333333,5.333333,17.400000,1.333333,0.333333,0.333333
11,2017-10-14,17:30,Premier League,Matchweek 8,Sat,Away,L,1.0,2.0,Watford,...,17,5,1.333333,0.000000,17.000000,5.000000,18.333333,1.666667,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,2022-12-26,15:00,Premier League,Matchweek 17,Mon,Away,W,2.0,1.0,Everton,...,15,0,1.000000,2.000000,10.333333,3.333333,19.566667,0.333333,0.333333,0.333333
19,2022-12-31,12:30,Premier League,Matchweek 18,Sat,Home,L,0.0,1.0,Manchester Utd,...,12,5,1.333333,2.000000,8.333333,3.333333,18.966667,0.333333,0.333333,0.333333
20,2023-01-04,20:00,Premier League,Matchweek 19,Wed,Away,D,1.0,1.0,Aston Villa,...,20,2,0.666667,1.333333,9.333333,3.000000,18.633333,1.000000,0.000000,0.000000
23,2023-01-14,15:00,Premier League,Matchweek 20,Sat,Home,W,1.0,0.0,West Ham,...,15,5,1.000000,1.000000,9.000000,3.333333,16.700000,0.666667,0.000000,0.000000
25,2023-01-22,14:00,Premier League,Matchweek 21,Sun,Away,L,0.0,3.0,Manchester City,...,14,6,0.666667,0.666667,12.333333,3.333333,17.166667,0.666667,0.000000,0.000000

In [17]:
matches_rolling.index = range(matches_rolling.shape[0])
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, error
combined, precision = make_predictions(matches_rolling, predictors + new_cols)
precision

0.6106870229007634

In [18]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)
combined

,actual,predicted,date,team,opponent,result
203,0,1,2023-01-03,Arsenal,Newcastle Utd,D
204,1,1,2023-01-15,Arsenal,Tottenham,W
205,1,0,2023-01-22,Arsenal,Manchester Utd,W
334,0,1,2023-01-04,Aston Villa,Wolves,D
335,1,0,2023-01-13,Aston Villa,Leeds United,W
...,...,...,...,...,...,...
3931,0,0,2023-01-14,West Ham United,Wolves,L
3932,1,1,2023-01-21,West Ham United,Everton,W
4099,0,0,2023-01-04,Wolverhampton Wanderers,Aston Villa,D
4100,1,0,2023-01-14,Wolverhampton Wanderers,West Ham,W
4101,0,0,2023-01-22,Wolverhampton Wanderers,Manchester City,L

In [19]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)
combined["new_team"] = combined["team"].map(mapping)
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,1,2023-01-04,Aston Villa,Wolves,D,Aston Villa,0,0,Wolverhampton Wanderers,Aston Villa,D,Wolves
4,1,0,2023-01-13,Aston Villa,Leeds United,W,Aston Villa,0,0,Leeds United,Aston Villa,L,Leeds United
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,0,0,2023-01-14,West Ham United,Wolves,L,West Ham,1,0,Wolverhampton Wanderers,West Ham,W,Wolves
59,1,1,2023-01-21,West Ham United,Everton,W,West Ham,0,0,Everton,West Ham,L,Everton
60,0,0,2023-01-04,Wolverhampton Wanderers,Aston Villa,D,Wolves,0,1,Aston Villa,Wolves,D,Aston Villa
61,1,0,2023-01-14,Wolverhampton Wanderers,West Ham,W,Wolves,0,0,West Ham United,Wolves,L,West Ham
62,0,0,2023-01-22,Wolverhampton Wanderers,Manchester City,L,Wolves,1,0,Manchester City,Wolves,W,Manchester City

In [20]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

0    9
1    6
Name: actual_x, dtype: int64